query GetHomeData($created_at: order_by = desc, $status: statuses_enum = published, $limit: Int = 2) {
  games(order_by: { created_at: $created_at }, where: { status: { _eq: $status } }) {
    id
    title
    description
    picture_url
    created_at
    dungeon_master {
      id
      username
    }
    players {
      user {
        id
        username
      }
    }
  }
  characters(limit: $limit, order_by: { created_at: $created_at }, where: { status: { _eq: $status } }) {
    id
    name
    picture
  }
}