query Objects ($kind: object_kind_enum = null, $status: statuses_enum = null) {
  objects(where: {kind: {_eq: $kind}, status: {_eq: $status}}, order_by: {name_ignore_accent: asc}) {
    id
    name
    kind
    picture_url
    status
    updated_at
    games {
      game {
        id
        title
      }
    }
  }
}
