#import '@/services/characters/Character.fragment.gql'

query CharacterQuery($characterId: uuid!) {
  character: characters_by_pk(id: $characterId) {
    ...Character
  }
  objects {
    id
    name
    description
    kind
    status
    can_be_equipped
  }
}
