query CharactersFromGame($gameId: uuid!) {
  characters(where: {game_id: {_eq: $gameId}}) {
    id
    name
    features
    maxHp: max_hp
    currentHp: current_hp
    picture
  }
  game: games_by_pk(id: $gameId) {
    title
  }
}
