query CharacterQuery($characterId: uuid!) {
  character: characters_by_pk(id: $characterId) {
    id
    name
    features
    maxHp: max_hp
    currentHp: current_hp
    picture
    description
    is_npc
    inventory
    items {
      id
      character_id
      object_id
      name
      bonus
      effect
      is_equipped
      quantity
      status
      kind
    }
  }
  objects {
    id
    name
    description
    kind
    status
    can_be_equipped
  }
}
