mutation CharacterMutation($characterId: uuid!, $name: String, $features: jsonb, $maxHp: Int, $currentHp: Int) {
  update_characters_by_pk(pk_columns: {id: $characterId}, _set: {name: $name, features: $features, max_hp: $maxHp, current_hp: $currentHp}) {
    id
    name
    features
    maxHp: max_hp
    currentHp: current_hp
  }
}